name: Deployment pipeline

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths-ignore:
      - "docs"
      - "README.md"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install packages
        run: npm i

      - name: Run linter
        run: npm run lint

  bump-version:
    runs-on: ubuntu-latest
    needs: build-and-test

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Automated Version Bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version-type: 'minor'

  deploy-prod:
    runs-on: ubuntu-latest
    needs: [build-and-test, bump-version]

    permissions:
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create deployment on Github
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: ${{ github.token }}
          environment-url: ${{ vars.RENDER_PUBLIC_URL }}
          environment: production
          initial-status: 'in_progress'

      - name: Trigger Render deployment
        run: curl -X GET https://api.render.com/deploy/${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_PROJECT_KEY }}

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ github.token }}
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: 'success'

      - name: Update deployment status (failure)
        if: failure() && steps.deployment.outputs.continue == 'true'
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ github.token }}
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: 'failure'
