name: Feature pipeline - complete deployment

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook

jobs:
  finish-deployment:
    runs-on: ubuntu-latest

    permissions:
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get latest deployment ID
        id: get_deployment_id
        run: |
          DEPLOYMENT_ID=$(curl -s -H "Authorization: Bearer ${{ github.token }}" \
                        "https://api.github.com/repos/${{ github.repository }}/deployments?environment=development" \
                        | jq -r '.[0].id')
          echo "Latest Deployment ID: $DEPLOYMENT_ID"
          echo "deployment_id=$DEPLOYMENT_ID" >> "$GITHUB_ENV"

      - name: Update deployment status (success)
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ github.token }}
          environment-url: ${{ vars.RENDER_DEV_URL }}
          deployment-id: "$deployment_id"
          state: 'failure'
